spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: keycloak
            authorization-grant-type: authorization_code
            client-authentication-method: none
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo
oauth2:
  registration-id: keycloak